name: Generate Node.js packages
run-name: Generate Node.js ${{ inputs.VERSION || '18.12.0' }}
on:
  workflow_dispatch:
    inputs:
      VERSION:
        description: 'Node.js version to build and upload'
        required: true
        default: '18.12.0'
      PUBLISH_RELEASES:
        description: 'Whether to publish releases'
        required: true
        type: boolean
        default: false
  pull_request:
    paths-ignore:
    - 'versions-manifest.json'
    - 'LICENSE'
    - '**.md'
    branches:
    - 'main'

jobs:
  node:
    name: Node
    uses: priyagupta108/versions-package-tools/.github/workflows/build-tool-packages.yml@main
    with:
      tool-name: "node"
      tool-version: ${{ inputs.VERSION || '18.12.0' }}
      publish-release: ${{ inputs.PUBLISH_RELEASES || false }}
    secrets: inherit